In [1]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import numpy as np

In [2]:
t1 = torch.Tensor(4, 6)
t2 = torch.tensor([3.2, 4.3, 5.5])
t3 = torch.tensor(np.array([[3.2], [4.3], [5.5]]))
t4 = torch.rand(4, 6)

#t5 = t1 + t2
t6 = t2 * t3
t7 = t2 @ t3.to(dtype=torch.float)

t8 = t1.view(2, 12) # (2, -1)

In [13]:
x = torch.tensor([1., 2., 3.], requires_grad = True)
y = torch.tensor([4., 5., 6.], requires_grad = True)

z = x + y
z_sum = torch.sum(z)
z_sum.backward()
print(x.grad)

tensor([1., 1., 1.])


In [16]:
x = torch.empty(5, 3)
y = torch.empty([5, 3])
a = torch.rand(5, 4)

tmp1 = torch.tensor([1,2])
tmp2 = torch.tensor([2,3])
print(tmp1 + tmp2)
print(torch.add(tmp1, tmp2))

tensor([3, 5])
tensor([3, 5])
